package views.components;

import java.awt.Color;
import javax.swing.JScrollBar;
import net.miginfocom.swing.MigLayout;
import views.swing.ScrollBar;

public class ChatBody extends javax.swing.JPanel {

    public ChatBody() {
        initComponents();
        init();
        addItemLeft("Hello anh ban chao anh ban nha aaaaaaaaaaaaa");
        addItemRight("378474747474747474");
        addItemLeft("Hello anh ban chao anh ban nha aaaaaaaaaaaaa");
        addItemRight("378474747474747474");
        addItemLeft("Hello anh ban chao anh ban nha aaaaaaaaaaaaa");
        addItemRight("378474747474747474");
        addItemLeft("Hello anh ban chao anh ban nha aaaaaaaaaaaaa");
        addItemRight("378474747474747474");
        addItemLeft("Hello anh ban chao anh ban nha aaaaaaaaaaaaa");
        addItemRight("378474747474747474");
        addItemLeft("Hello anh ban chao anh ban nha aaaaaaaaaaaaa");
        addItemRight("378474747474747474");
        addItemLeft("Hello anh ban chao anh ban nha aaaaaaaaaaaaa");
        addItemRight("378474747474747474");
        addItemLeft("Hello anh ban chao anh ban nha aaaaaaaaaaaaa");
        addItemRight("378474747474747474");
        addItemLeft("Hello anh ban chao anh ban nha aaaaaaaaaaaaa");
        addItemLeft("Hello anh ban chao anh ban nha aaaaaaaaaaaaa");
        addItemRight("378474747474747474");
        addItemLeft("Hello anh ban chao anh ban nha aaaaaaaaaaaaa");
        addItemRight("378474747474747474");
        addItemLeft("Hello anh ban chao anh ban nha aaaaaaaaaaaaa");
        addItemRight("378474747474747474");
        addItemLeft("Hello anh ban chao anh ban nha aaaaaaaaaaaaa");
        addItemRight("378474747474747474");
        addItemLeft("Hello anh ban chao anh ban nha aaaaaaaaaaaaa");
        addItemRight("378474747474747474");
    }

    private void init() {
        body.setLayout(new MigLayout("fillx", "", "5[]5"));
        sp.setVerticalScrollBar(new ScrollBar());
        sp.getVerticalScrollBar().setBackground(Color.WHITE);
    }

    public void addItemLeft(String text) {
        ChatLeft item = new ChatLeft();
        item.setText(text);
        body.add(item, "wrap, w ::80%");
        //  ::80% set max with 80%
        body.repaint();
        body.revalidate();
    }
    
    public void addItemRight(String text) {
        ChatRight item = new ChatRight();
        item.setText(text);
        body.add(item, "wrap, al right, w ::80%");
        //  ::80% set max with 80%
        body.repaint();
        body.revalidate();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        sp = new javax.swing.JScrollPane();
        body = new javax.swing.JPanel();

        sp.setBackground(new java.awt.Color(255, 255, 255));
        sp.setBorder(null);
        sp.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);

        body.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout bodyLayout = new javax.swing.GroupLayout(body);
        body.setLayout(bodyLayout);
        bodyLayout.setHorizontalGroup(
            bodyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 667, Short.MAX_VALUE)
        );
        bodyLayout.setVerticalGroup(
            bodyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 564, Short.MAX_VALUE)
        );

        sp.setViewportView(body);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(sp)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(sp)
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel body;
    private javax.swing.JScrollPane sp;
    // End of variables declaration//GEN-END:variables
}
